### ISSUE TITLE
data race in expirationCheck()

### ISSUE THREAD

**Issue by jrmarkle** [rif/cache2go#8]
I think there's a race in expirationCheck() because the following code snippet doesn't do what you want (based on the comment).

```
// Cache value so we don't keep blocking the mutex.
items := table.items
table.Unlock()
```

In go, maps hold references to an underlying data structure. So here `items` simply points to to `table.items` and it is not safe to unlock the table.

**Comment by rif** [comment]
Hi @jrmarkle, this library is no longer maintained here. Please check the code on this fork https://github.com/muesli/cache2go and open the issue there if it's still needed.

**Comment by muesli** [comment]
Fwiw, I still think this is correct. It's not the underlying data we're trying to protect, it's the map itself (which could get changed during the expirationCheck).
